### ISSUE TITLE
ERROR: Error from Terminal-Profiles.TerminalProfiles.on_catalog: <class 'TypeError'>: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by tiredcisadmin** [fran-f/keypirinha-terminal-profiles#5]
I'm sure it's something I have mis-configured but I can not tell what from the error. Windows Terminal does appear to be installed to the directory in which it is being looked for (C:\Users\%USER\AppData\Local\Microsoft\WindowsApps\wt.exe)

```
** ERROR: Error from Terminal-Profiles.TerminalProfiles.on_catalog: <class 'TypeError'>: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\%USER\Downloads\Programs\keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\TerminalProfiles.py", line 54, in on_catalog
  File "C:\Users\%USER\Downloads\Programs\keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\TerminalProfiles.py", line 54, in <listcomp>
  File "C:\Users\%USER\Downloads\Programs\keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\TerminalProfiles.py", line 97, in _item_for_profile
  File "C:\Users\%USER\Downloads\Programs\keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\TerminalProfiles.py", line 116, in _load_profile_icon
```

**Comment by fran-f** [comment]
~This could be caused by a Terminal profile without a `guid` field. Could you double check your Terminal configuration?~

Uhm no, probably not that. Are you using the stable version, or Terminal Preview?

**Comment by tiredcisadmin** [comment]
I believe I am on the stable now.

Windows Terminal
Version: 1.1.2021.0

https://github.com/microsoft/terminal/releases/tag/v1.1.2021.0

**Comment by fran-f** [comment]
Yep, 1.1 has reached stable recently. Could you attach your Terminal configuration here, please? (double check to remove and sensitive data that might be in there!)

**Comment by tiredcisadmin** [comment]
```
// This file was initially generated by Windows Terminal 1.0.1401.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",

    // You can add more global application settings here.
    // To learn more about global settings, visit https://aka.ms/terminal-global-settings

    // If enabled, selections are automatically copied to your clipboard.
    "copyOnSelect": true,

    // If enabled, formatted data is also copied to your clipboard
    "copyFormatting": false,

    // A profile specifies a command to execute paired with information about how it should look and feel.
    // Each one of them will appear in the 'New Tab' dropdown,
    //   and can be invoked from the commandline with `wt.exe -p xxx`
    // To learn more about profiles, visit https://aka.ms/terminal-profile-settings
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
        },
        "list":
        [
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "cursorShape": "filledBox",
                "fontSize": 9,
                "hidden": false
            },
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe",
                "experimental.retroTerminalEffect": true,
                "colorScheme": "Retro",
                "cursorShape": "vintage",
                "fontFace": "PxPlus IBM VGA8",
                "hidden": false
            },
            {
                "guid": "{a5a97cb8-8961-5535-816d-772efe0c6a3f}",
                "hidden": false,
                "name": "Arch",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{1777cdf0-b2c4-5a63-a204-eb60f349ea7c}",
                "hidden": false,
                "name": "Alpine",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{a8202b0e-781a-5dab-98e2-e9d469a63619}",
                "hidden": false,
                "name": "CentOS7",
                "source": "Windows.Terminal.Wsl"
            },
            
            {
                "guid": "{58ad8b0c-3ef8-5f4d-bc6f-13e4c00f2530}",
                "hidden": false,
                "name": "Debian",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{50bb7549-6775-516b-925e-4bbdae6c2b17}",
                "hidden": false,
                "name": "Fedora31",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{46ca431a-3a87-5fb3-83cd-11ececc031d2}",
                "hidden": false,
                "name": "kali-linux",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{b2d6503a-d0e6-5c93-b063-25b165a68977}",
                "hidden": false,
                "name": "openSUSE-42",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{c27d95cb-d368-5c23-be06-9170eac50e34}",
                "hidden": false,
                "name": "RHWSL",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{802ac638-da66-5c78-afa2-28bf0bc5cb3f}",
                "hidden": false,
                "name": "SLES-12",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
                "hidden": false,
                "name": "Ubuntu-20.04",
                "cursorShape": "filledBox",
                "fontSize": 9,
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
                "hidden": false,
                "name": "Ubuntu-18.04",
                "cursorShape": "filledBox",
                "fontSize": 9,
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{6f9994f0-4403-5e85-9cce-98e5da3839bb}",
                "hidden": false,
                "name": "Ubuntu-16.04",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu-server",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{342eaa22-06b2-5df7-b78e-a6046a4926db}",
                "hidden": false,
                "name": "Void",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }

        ]
    },

    // Add custom color schemes to this array.
    // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
    "schemes": 
    [
        {
            "name": "Retro",
            "background": "#000000",
            "black": "#00ff00",
            "blue": "#00ff00",
            "brightBlack": "#00ff00",
            "brightBlue": "#00ff00",
            "brightCyan": "#00ff00",
            "brightGreen": "#00ff00",
            "brightPurple": "#00ff00",
            "brightRed": "#00ff00",
            "brightWhite": "#00ff00",
            "brightYellow": "#00ff00",
            "cyan": "#00ff00",
            "foreground": "#00ff00",
            "green": "#00ff00",
            "purple": "#00ff00",
            "red": "#00ff00",
            "white": "#00ff00",
            "yellow": "#00ff00"
        }
    ],

    // Add custom keybindings to this array.
    // To unbind a key combination from your defaults.json, set the command to "unbound".
    // To learn more about keybindings, visit https://aka.ms/terminal-keybindings
    "keybindings":
    [
        // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
        // These two lines additionally bind them to Ctrl+C and Ctrl+V.
        // To learn more about selection, visit https://aka.ms/terminal-selection
        { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" },
        { "command": "paste", "keys": "ctrl+v" },

        // Press Ctrl+Shift+F to open the search box
        { "command": "find", "keys": "ctrl+shift+f" },

        // Press Alt+Shift+D to open a new pane.
        // - "split": "auto" makes this pane open in the direction that provides the most surface area.
        // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
        // To learn more about panes, visit https://aka.ms/terminal-panes
        { "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "alt+shift+d" }
    ]
}
```

**Comment by fran-f** [comment]
Uhm... your configuration loads fine here, but I only have one Linux distribution installed.

Could you try with this test release? It adds a check for the error you see, and extra debug output in the console. It might solve your immediate problem, and help us investigate further.
https://github.com/fran-f/keypirinha-terminal-profiles/releases/tag/v1.5

(edit: fixed link)

**Comment by tiredcisadmin** [comment]
So installed that and some loaded. 
```
Terminal-Profiles.TerminalProfiles: Adding profile 'Windows PowerShell' {61c54bbd-c2c6-5271-96e7-009a87ff44bf}
Apps.Desktop: Cataloged 15 items in 0.2 seconds
Apps.StartMenu: Cataloged 190 items in 0.2 seconds
Terminal-Profiles.TerminalProfiles: Adding profile 'essupp' None
** ERROR: Error from Terminal-Profiles.TerminalProfiles.on_catalog: <class 'AttributeError'>: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "C:\Users\jreed\Downloads\Programs\keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\TerminalProfiles.py", line 54, in on_catalog
  File "C:\Users\jreed\Downloads\Programs\keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\TerminalProfiles.py", line 54, in <listcomp>
  File "C:\Users\jreed\Downloads\Programs\keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\TerminalProfiles.py", line 99, in _item_for_profile
  File "C:\Users\jreed\Downloads\Programs\keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\TerminalProfiles.py", line 122, in _load_profile_icon
```
Then I folowed.
```
Terminal-Profiles.TerminalProfiles: Adding profile 'essupp' None
** ERROR: Error from Terminal-Profiles.TerminalProfiles.on_catalog: <class 'AttributeError'>: 'NoneType' object has no attribute 'startswith'
```
and realized I missed a comma...

**Comment by fran-f** [comment]
Glad you find the issue!

On my side, I have added some validation, and a more useful error message. [Version 1.4](https://github.com/fran-f/keypirinha-terminal-profiles/releases/tag/v1.4) is out.

**Comment by tiredcisadmin** [comment]
awesome!

**Comment by tiredcisadmin** [comment]
Just updated and
```
15:32:20.941 Plugin loaded: Terminal-Profiles.TerminalProfiles (instance #2)
15:32:20.956 ** ERROR: Error from Terminal-Profiles.TerminalProfiles.on_catalog: <class 'json.decoder.JSONDecodeError'>: Expecting property name enclosed in double quotes: line 1 column 601 (char 600)
Traceback (most recent call last):
  File "C:\Users\jreed\Downloads\Programs\keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\TerminalProfiles.py", line 54, in on_catalog
  File "C:\Users\jreed\Downloads\Programs\keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\lib\WindowsTerminalWrapper.py", line 35, in profiles
  File "lib\json\__init__.py", line 348, in loads
  File "lib\json\decoder.py", line 337, in decode
  File "lib\json\decoder.py", line 353, in raw_decode
```

**Comment by fran-f** [comment]
> Expecting property name enclosed in double quotes

This is JSON parser error, and seems unrelated to my changes.

~Maybe your Terminal configuration contains something like~  ← wrong, see below
```
  property: "value"
```
that should look like this instead
```
  "property": "value"
```

**Comment by tiredcisadmin** [comment]
Possibly, I don't see it off hand. There is no line 1 column 601 (char 600) that I can find though.

**Comment by fran-f** [comment]
Line numbers will not match, because I have to convert the file before parsing it. (Terminal uses the "jsonc" format, JSON + comments, which Python cannot easily parse; the solution is to "minify" the file, removing the comments first, and that messes up the lines numbers).

Opening the configuration file in a code editor should help you spot any issues. I'm surprised Terminal itself does not complain about it though 🤔

**Comment by tiredcisadmin** [comment]
I have it open in VScode. That's what I use to edit it so that's what I used to try to find the error.

**Comment by fran-f** [comment]
> Expecting property name enclosed in double quotes

I discovered that this error happens when you have a comma at the end of the last line of an object. Like this for example:
```json
"defaults":
{
    "fontFace": "Consolas",
    "fontSize": 11,   ← this comma should not be there
}
```
These are also JSONC syntax, that a basic JSON parser shows as errors. I'll investigate alternatives, so that the plugin can support the full syntax.
