### ISSUE TITLE
Terminals does not show up in launchbox, fails to load icon

### ISSUE THREAD

**Issue by Crimix** [fran-f/keypirinha-terminal-profiles#8]
From the log it fails with the following
```
06:52:44.674 ** ERROR: Error from Terminal-Profiles.TerminalProfiles.on_catalog: <class 'OSError'>: [Errno 22] Invalid argument: 'file:///c:/Users/name/icons/icon.png'
Traceback (most recent call last):
  File "C:\Users\name\Keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\terminal_profiles.py", line 66, in on_catalog
  File "C:\Users\name\Keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\terminal_profiles.py", line 67, in <listcomp>
  File "C:\Users\name\Keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\terminal_profiles.py", line 119, in _item_for_profile
  File "C:\Users\name\Keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\terminal_profiles.py", line 157, in _load_profile_icon
  File "lib\shutil.py", line 120, in copyfile
```

**Comment by fran-f** [comment]
I hadn't though about paths using the `file:` protocol! In my configuration, I use normal Windows paths, so I can use environment variables like `%APPDATA%`.

The [new version](https://github.com/fran-f/keypirinha-terminal-profiles/releases/tag/v1.7) should fix that 🙂

**Comment by Crimix** [comment]
Thank you for the fast response, I will test it on my machine tomorrow 🙂

**Comment by Crimix** [comment]
It works 🙂

**Comment by fran-f** [comment]
Sounds great! Closing this then, thank you for reporting it.
